/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package defaultpackage;

import defaultpackage.Connecter;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kévin Bloomfield
 */
public class GaiImmo extends javax.swing.JFrame {

    /**
     * Creates new form GaiImmo
     */
    Connecter con=new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model=new DefaultTableModel();
    public GaiImmo() {
        initComponents();
        
        model.addColumn("idDemande");
        model.addColumn("idPersonne");
        model.addColumn("genre");
        model.addColumn("ville");
        model.addColumn("budget");
        model.addColumn("superficie");
        model.addColumn("categorie");
        try{
        stm=con.obtenirconnexion().createStatement();
        ResultSet Rs=stm.executeQuery("Select * from demande");
        while(Rs.next()){
        model.addRow(new Object[]{Rs.getString("idDemande"),Rs.getString("idPersonne"),Rs.getString("genre"),Rs.getString("ville"),Rs.getString("budget"),
           Rs.getString("superficie"),Rs.getString("categorie")});
            
        }
    }catch(Exception e) {System.err.println(e);}
    
    tble.setModel(model);    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtidDem = new javax.swing.JTextField();
        txtidPers = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        txtVille = new javax.swing.JTextField();
        txtBud = new javax.swing.JTextField();
        txtSpf = new javax.swing.JTextField();
        txtCat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("idDemande : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 90, 17);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("idPersonne :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 40, 80, 17);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setText("genre : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 70, 70, 17);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setText("ville :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 100, 70, 17);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel5.setText("budget :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 130, 60, 17);

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel6.setText("superficie :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 160, 80, 17);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel7.setText("catégorie :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 190, 80, 17);

        txtidDem.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        txtidDem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidDemActionPerformed(evt);
            }
        });
        jPanel1.add(txtidDem);
        txtidDem.setBounds(100, 10, 90, 20);

        txtidPers.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        txtidPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidPersActionPerformed(evt);
            }
        });
        jPanel1.add(txtidPers);
        txtidPers.setBounds(100, 40, 90, 20);

        txtGenre.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        txtGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenreActionPerformed(evt);
            }
        });
        jPanel1.add(txtGenre);
        txtGenre.setBounds(100, 70, 90, 22);

        txtVille.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jPanel1.add(txtVille);
        txtVille.setBounds(100, 100, 90, 22);

        txtBud.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jPanel1.add(txtBud);
        txtBud.setBounds(100, 130, 90, 22);

        txtSpf.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        txtSpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpfActionPerformed(evt);
            }
        });
        jPanel1.add(txtSpf);
        txtSpf.setBounds(100, 160, 90, 22);

        txtCat.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        txtCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatActionPerformed(evt);
            }
        });
        jPanel1.add(txtCat);
        txtCat.setBounds(100, 190, 90, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 60, 210, 240);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 60, 550, 140);

        jButton1.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 320, 80, 30);

        jButton2.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 360, 80, 30);

        jButton3.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jButton3.setText("Actualiser");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 320, 90, 30);

        jButton4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(160, 360, 90, 30);

        jButton5.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(280, 360, 120, 30);

        txtre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreActionPerformed(evt);
            }
        });
        getContentPane().add(txtre);
        txtre.setBounds(420, 360, 210, 30);

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel8.setText("GESTION DES DEMANDES ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 10, 220, 30);
        jLabel8.getAccessibleContext().setAccessibleDescription("");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kévin Bloomfield\\Pictures\\fond-ecran-wallpaper-image-abstrait-bleu-13.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 870, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void deplace(int i){
try{
txtidDem.setText(model.getValueAt(i,0).toString());
txtidPers.setText(model.getValueAt(i,1).toString());
txtGenre.setText(model.getValueAt(i,2).toString());
txtVille.setText(model.getValueAt(i,3).toString());
txtBud.setText(model.getValueAt(i,4).toString());
txtSpf.setText(model.getValueAt(i,5).toString());
txtCat.setText(model.getValueAt(i,6).toString());
}catch (Exception e){System.err.println(e);
JOptionPane.showMessageDialog(null,"erreur de déplacement"+e.getLocalizedMessage());}
}

private void afficher(){
try{
        model.setRowCount(0);
        stm=con.obtenirconnexion().createStatement();
        ResultSet Rs=stm.executeQuery("Select * from demande");
        while(Rs.next()){
        model.addRow(new Object[]{Rs.getString("idDemande"),Rs.getString("idPersonne"),Rs.getString("genre"),Rs.getString("ville"),Rs.getString("budget"),
           Rs.getString("superficie"),Rs.getString("categorie")});
            
        }
    }catch(Exception e) {System.err.println(e);}
    
    tble.setModel(model); 
}
    private void txtidDemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidDemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidDemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String idDemande=txtidDem.getText();
        String idPersonne=txtidPers.getText();
        String genre=txtGenre.getText();
        String ville=txtVille.getText();
        String budget=txtBud.getText();
        String superficie=txtSpf.getText();
        String categorie=txtCat.getText();
        String requete="Insert into demande(idDemande, idPersonne, genre, ville, budget, superficie, categorie) VALUES('"+
                idDemande+"','"+idPersonne+"','"+genre+"','"+ville+"','"+budget+"','"+superficie+"','"+categorie+"')";
        try{
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null,"Le demandeur a été ajouté");
            txtidPers.setText("");
            txtGenre.setText("");
            txtVille.setText("");
            txtBud.setText("");
            txtSpf.setText("");
            txtCat.setText("");
            afficher();
                    
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                   JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
           
            stm.executeUpdate("UPDATE demande SET idPersonne='"+txtidPers.getText()+"',genre='"+txtGenre.getText()+"',ville='"+txtVille.getText()+
                    "',budget='"+txtBud.getText()+"'superficie='"+txtSpf.getName()+
                    "' WHERE idDemande= "+txtidDem.getText());
            afficher();
         }
      } catch (Exception e){JOptionPane.showMessageDialog(null,"erreur veuillez le modifier !!!!"+e.getMessage());
      System.err.println(e);
  }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
afficher();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtidPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidPersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidPersActionPerformed

    private void txtCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatActionPerformed

    private void txtreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreActionPerformed

    private void txtGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenreActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
try{
int i=tble.getSelectedRow();
deplace(i);
}catch(Exception e){JOptionPane.showMessageDialog(null,"problème de déplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tbleMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try{
          if 
            (JOptionPane.showConfirmDialog (null,"Etes-vous sur de supprimer cette demande ?",
                    "Supprimer une demande", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
            
          
           if(txtidDem.getText().length() != 0){
          stm.executeUpdate("Delete From demande WHERE idDemande= "+txtidDem.getText());
          afficher();
           }
           else { 
           JOptionPane.showMessageDialog(null,"Vous devez remplir le champ idDemande !");}
          }catch (Exception e){
           JOptionPane.showMessageDialog(null,"Erreur de suppression \n"+e.getMessage());}            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try{
           model.setRowCount(0); //pour vider la liste des demandes
           {
           Rs=stm.executeQuery("Select * from demande WHERE idPersonne = '"+txtre.getText()+"'");
           }while (Rs.next()){
           
           Object [] demande={Rs.getString(1),Rs.getString(2),Rs.getString(3),Rs.getString(4),Rs.getString(5),Rs.getString(6),Rs.getString(7)};
           model.addRow(demande);
           } if (model.getRowCount () == 0){
               JOptionPane.showMessageDialog(null,"Il y a pas de demande");
       
           } else{ int i=0;
           deplace(i);
           }
                     
       }catch (Exception e) { System.err.println(e);
       JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtSpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpfActionPerformed

  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaiImmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaiImmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaiImmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaiImmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GaiImmo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tble;
    private javax.swing.JTextField txtBud;
    private javax.swing.JTextField txtCat;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtSpf;
    private javax.swing.JTextField txtVille;
    private javax.swing.JTextField txtidDem;
    private javax.swing.JTextField txtidPers;
    private javax.swing.JTextField txtre;
    // End of variables declaration//GEN-END:variables
}
